## Import

In [1]:
import pandas as pd
import os

# Isso aqui limpa a "confusão" que o Python 3.13 está fazendo
if 'MPLBACKEND' in os.environ:
    del os.environ['MPLBACKEND']
import matplotlib
# Isso avisa ao programa: "Ei, desenhe o gráfico aqui dentro do Jupyter mesmo!"
matplotlib.use('Agg')
from ImpararePackage import dataRequest

from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix, classification_report

from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
from sklearn import tree

import joblib

import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
query = """
select 
    pa."caso infeccao",
    pa."caso infeccao hospitalar",
    pa."Conjuntivite",
    pa."Infecção da cavidade oral",
    pa."Infecção de pele",
    pa."Meningite",
    pa.comunitaria,
    pa.enterocolite,
    pa.ipcs,
    pa.isc,
    pa.pav,
    dtp.*
from imparare2_train_wellhead_set_prepared dtp
inner join new_avaliacao_padrao_ouro pa
    on dtp."REGISTRO" = pa.registro 
        and dtp."DIA_parsed" = pa.dt_infeccao
"""

df = dataRequest.get_data(queryText= query, chunck= None)

In [8]:
df.head()

,caso infeccao,caso infeccao hospitalar,Conjuntivite,Infecção da cavidade oral,Infecção de pele,Meningite,comunitaria,enterocolite,ipcs,isc,pav,REGISTRO,DIA_parsed,SEXO,IDADE,UNIDADE_INTERNACAO,ESPECIALIDADE_INTERNACAO,TIPO_INTERNACAO,CLINICA_INTERNACAO,dthr_internacao,dthr_alta,los_dias,los_horas,CIRURGIA_tempo_total,CIRURGIA_procedimentos_total,TECNICO(A) EM ENFERMAGEM_count,TECNICO(A) EM ENFERMAGEM_avg,ENFERMEIRO(A)_count,ENFERMEIRO(A)_avg,AUXILIAR DE ENFERMAGEM_count,AUXILIAR DE ENFERMAGEM_avg,ACADEMICODE ENFERMAGEM_count,ACADEMICO DE ENFERMAGEM_avg,MEDICO_count,MEDICO_avg,FISIOTERAPEUTA_count,FISIOTERAPEUTA_avg,OUTROS_count,OUTROS_avg,DIUR_min,DIUR_max,DIUR_count,DIUR_avg,DIUR_stddev,DIUR_delta,FC_min,FC_max,FC_ALTERADA,FC_ALTA,FC_BAIXA,FC_count,FC_avg,FC_stddev,FC_delta,FR_min,FR_max,FR_ALTERADA,FR_count,FR_avg,FR_stddev,FR_delta,HGT_min,HGT_max,HGT_ALTERADO,HGT_count,HGT_avg,HGT_stddev,HGT_delta,OXIMETRIA_min,OXIMETRIA_max,OXIMETRIA_count,OXIMETRIA_avg,OXIMETRIA_stddev,OXIMETRIA_delta,PAD_min,PAD_max,PAD_count,PAD_avg,PAD_stddev,PAD_delta,PAS_min,PAS_max,PAS_count,PAS_avg,PAS_stddev,PAS_delta,TEMP_min,TEMP_max,TEMP_ALTERADA,TEMP_ALTA,TEMP_BAIXA,TEMP_count,TEMP_avg,TEMP_stddev,TEMP_delta,PA_min,PA_max,PA_count,PA_avg,PA_stddev,PA_delta,PAM_min,PAM_max,PAM_count,PAM_avg,PAM_stddev,PAM_delta,O2_min,O2_max,O2_count,O2_avg,O2_stddev,O2_delta,FIO2_min,FIO2_max,FIO2_count,FIO2_avg,FIO2_stddev,FIO2_delta,PEEP_min,PEEP_max,PEEP_count,PEEP_avg,PEEP_stddev,PEEP_delta,SINAIS_VITAIS_registros_total,UNIDADE_fim_janela,UNIDADE_inicio_janela,UNIDADE_movimento_total,EVOLUCAO_notas_total,EVOLUCAO_notas_total_dia,aciclovir_count,amoxicilina_sulbactam_count,cefadroxila_count,cefalotina_count,cefotaxima_count,ceftazidima_count,ceftazidima_avibactam_count,ceftalozana_tazobactam_count,cetoconazol_count,claritromicina_count,cloranfenicol_count,doxiciclina_count,ertapenem_count,eritromicina_count,ganciclovir_count,ivermectina_count,micafungina_count,miconazol_count,moxifloxacino_count,mupirocina_count,neomicina_count,rifampicina_count,sulfadiazina_count,teicoplanina_count,voriconazol_count,ciprofloxacino_count,outro_count,amicacina_count,amoxicilina_clavulanato_count,amoxicilina_count,ampicilina_count,azitromicina_count,penicilinagbenzatina_count,penicilinagpotassica_count,cefalexina_count,cefazolina_count,cefepima_count,ceftriaxona_count,cefuroxima_count,clindamicina_count,fluconazol_count,gentamicina_count,levofloxacino_count,linezolida_count,meropenem_count,metronidazol_count,nistatina_count,oxacilina_count,piperacilina_tazobactam_count,ampicilina_sulbactam_count,sulfametoxazol_trimetoprim_count,polimixinab_count,tobramicina_count,vancomicina_count,via_topico_count,via_sng_count,via_outro_count,via_ev_count,via_im_count,via_vo_count,agg_hemocultura,qtd_hemocultura_positiva,qtd_hemocultura_sem_crescimento,qtd_cultura_positiva,qtd_cultura_sem_crescimento,qtd_bacteroscopico_positiva,qtd_bacteroscopico_negativa,agg_urocultura,qtd_urocultura_positiva,qtd_urocultura_sem_crescimento,qtd_bacteriologico_positiva,qtd_bacteriologico_sem_crescimento,leuco_min,leuco_max,leuco_avg,rdw_min,rdw_max,rdw_avg,neuto_min,neuto_max,neuto_avg,LEUCO_ALTERADO,LEUCO_ALTO,LEUCO_BAIXO,RDW_ALTO,NEUTROFILO_ALTO,RAGIOLOGIA_laudos_total,tosse,ronco,cavita,opac,infil,fibrose_cistica,sec_pur_pulmonar,secr,puru,secr_traq,o2,dpoc,hemoptise,leucemia,esplenectomia,febre,consol,linfoma,acinetobacter,amarelada,aspiracao,broncograma_aereo,crepitante,enterobacter,enterococcus,hemophylus,hipertermia,imunossuprimido,infeccao,klebsiella,legionella,leucocitose,leucopenia,moraxella,pneumococcus,pseudomonas,sibilos,intubacao,staphylococcus_aureus,sepse_pulmonar,sepse_respiratoria,sepse_urinaria,padrao_ventilatorio,insuficiencia_ventilatoria,esforco_ventilatorio,lavado_broncoalveolar,derrame_pleural,escherichia_coli,choque_septico,dor_pleuritica,dor_ventilatorio_dependente,ventilacao_mecanica,iot,pav,endoftalmite,eritema,hiperemia,mediastinite,staphylococcus_coagulase_negativo,supuracao,rubor,mal_estar,abscesso,calor,dreno,edema,endocardite,antibiotico,bacteriologico,deiscencia,resistente,taquicardia,cateter,cateter_arterial,cateter_urinario,cvc,cateter_venoso_periferico,clorose,instabilidade,oliguria,hipotensao,anuria,bacteremia,bacteriuria,disuria,leucocituria,nitrito,svd,tsa,choque,staphylococcus,e_coli,colecao,tremor,calafrio,pos_operatorio,dor_suprapubica,foco_urinario,colite_pseudomembranosa,yersinia,vomito,shigella,salmonela,nausea,giardia,dor_cabeca,dor_abdominal,diarreia,clostridium,campylobacter,urgencia_urinaria,urgencia_miccional,sondagem_alivio,sondagem_vesical,urocultura,piuria,albumina,press_parc_co2,bicarbonato,calcio,creatinina,glicose,hemoglobina,plaquetas,potassio,sodio,bilirrubina,cardiomegalia,lesao_pulmonar,pneumonia,atelectasia,pneumotorax,fratura,freq_respiratoria,freq_cardiaca,pressao_sanguinea,saturacao_sangue,hemocultura,temperatura,ph_sangue,propionibacterium,cryptococcus,pneumocystis,histoplasma,paracoccidioides,bacteroides,candida,fusobacterium,peptostreptococcus,sibilancia,hipotermia,apneia,bradicardia,streptococcus_viridans,consciencia,hcm,hgm,corynebacterium,bacillus,aerococcus,coccidioides,veillonella,covid,peep,fio2,spo2,avc,sne,desnutricao,sedacao,vsg,fosfatase_alcalina,ldh,cetamina,propofol,clorpromazina,fentanil,pancuronio,noradrenalina,diazepan,lorazepan,flumazenil,clonidina,npt,cateter_monolumen,cateter_duplolumen,cateter_triplolumen,portocath,cateter_hickmann,shilley,obesidade,diabetes,neutropenia,tabagismo,tosse_pos_count,ronco_pos_count,cavita_pos_count,opac_pos_count,infil_pos_count,fibrose_cistica_pos_count,sec_pur_pulmonar_pos_count,secr_pos_count,puru_pos_count,secr_traq_pos_count,o2_pos_count,dpoc_pos_count,hemoptise_pos_count,leucemia_pos_count,esplenectomia_pos_count,febre_pos_count,consol_pos_count,linfoma_pos_count,acinetobacter_pos_count,amarelada_pos_count,aspiracao_pos_count,broncograma_aereo_pos_count,crepitante_pos_count,enterobacter_pos_count,enterococcus_pos_count,hemophylus_pos_count,hipertermia_pos_count,imunossuprimido_pos_count,infeccao_pos_count,klebsiella_pos_count,legionella_pos_count,leucocitose_pos_count,leucopenia_pos_count,moraxella_pos_count,pneumococcus_pos_count,pseudomonas_pos_count,sibilos_pos_count,intubacao_pos_count,staphylococcus_aureus_pos_count,sepse_pulmonar_pos_count,sepse_respiratoria_pos_count,sepse_urinaria_pos_count,padrao_ventilatorio_pos_count,insuficiencia_ventilatoria_pos_count,esforco_ventilatorio_pos_count,lavado_broncoalveolar_pos_count,derrame_pleural_pos_count,escherichia_coli_pos_count,choque_septico_pos_count,dor_pleuritica_pos_count,dor_ventilatorio_dependente_pos_count,ventilacao_mecanica_pos_count,iot_pos_count,pav_pos_count,endoftalmite_pos_count,eritema_pos_count,hiperemia_pos_count,mediastinite_pos_count,staphylococcus_coagulase_negativo_pos_count,supuracao_pos_count,rubor_pos_count,mal_estar_pos_count,abscesso_pos_count,calor_pos_count,dreno_pos_count,edema_pos_count,endocardite_pos_count,antibiotico_pos_count,bacteriologico_pos_count,deiscencia_pos_count,resistente_pos_count,taquicardia_pos_count,cateter_pos_count,cateter_arterial_pos_count,cateter_urinario_pos_count,cvc_pos_count,cateter_venoso_periferico_pos_count,clorose_pos_count,instabilidade_pos_count,oliguria_pos_count,hipotensao_pos_count,anuria_pos_count,bacteremia_pos_count,bacteriuria_pos_count,disuria_pos_count,leucocituria_pos_count,nitrito_pos_count,svd_pos_count,tsa_pos_count,choque_pos_count,staphylococcus_pos_count,e_coli_pos_count,colecao_pos_count,tremor_pos_count,calafrio_pos_count,pos_operatorio_pos_count,dor_suprapubica_pos_count,foco_urinario_pos_count,colite_pseudomembranosa_pos_count,yersinia_pos_count,vomito_pos_count,shigella_pos_count,salmonela_pos_count,nausea_pos_count,giardia_pos_count,dor_cabeca_pos_count,dor_abdominal_pos_count,diarreia_pos_count,clostridium_pos_count,campylobacter_pos_count,urgencia_urinaria_pos_count,urgencia_miccional_pos_count,sondagem_alivio_pos_count,sondagem_vesical_pos_count,urocultura_pos_count,piuria_pos_count,albumina_pos_count,press_parc_co2_pos_count,bicarbonato_pos_count,calcio_pos_count,creatinina_pos_count,glicose_pos_count,hemoglobina_pos_count,plaquetas_pos_count,potassio_pos_count,sodio_pos_count,bilirrubina_pos_count,cardiomegalia_pos_count,lesao_pulmonar_pos_count,pneumonia_pos_count,atelectasia_pos_count,pneumotorax_pos_count,fratura_pos_count,freq_respiratoria_pos_count,freq_cardiaca_pos_count,pressao_sanguinea_pos_count,saturacao_sangue_pos_count,hemocultura_pos_count,temperatura_pos_count,ph_sangue_pos_count,propionibacterium_pos_count,cryptococcus_pos_count,pneumocystis_pos_count,histoplasma_pos_count,paracoccidioides_pos_count,bacteroides_pos_count,candida_pos_count,fusobacterium_pos_count,peptostreptococcus_pos_count,sibilancia_pos_count,hipotermia_pos_count,apneia_pos_count,bradicardia_pos_count,streptococcus_viridans_pos_count,consciencia_pos_count,hcm_pos_count,hgm_pos_count,corynebacterium_pos_count,bacillus_pos_count,aerococcus_pos_count,coccidioides_pos_count,veillonella_pos_count,covid_pos_count,peep_pos_count,fio2_pos_count,spo2_pos_count,avc_pos_count,sne_pos_count,desnutricao_pos_count,sedacao_pos_count,vsg_pos_count,fosfatase_alcalina_pos_count,ldh_pos_count,cetamina_pos_count,propofol_pos_count,clorpromazina_pos_count,fentanil_pos_count,pancuronio_pos_count,noradrenalina_pos_count,diazepan_pos_count,lorazepan_pos_count,flumazenil_pos_count,clonidina_pos_count,npt_pos_count,cateter_monolumen_pos_count,cateter_duplolumen_pos_count,cateter_triplolumen_pos_count,portocath_pos_count,cateter_hickmann_pos_count,shilley_pos_count,obesidade_pos_count,diabetes_pos_count,neutropenia_pos_count,tabagismo_pos_count,pneumatose_sent_pos,piora_troca_gasosa_sent_pos,fontanela_abaulada_sent_pos,glicose_liquor_sent_pos,prote_liquor_sent_pos,leuco_liquor_sent_pos,bacteria_liquor_sent_pos,irritabilidade_sent_pos,cultura_liquor_sent_pos,hipoativ_sent_pos,dren_serosa_sent_pos,necrose_intestinal_sent_pos,intestino_fixo_sent_pos,sangue_fezes_sent_pos,convulsao_sent_pos,pneumoperitonio_sent_pos,dist_abdominal_sent_pos,asp_bilioso_sent_pos,pcr_sent_pos,letargia_sent_pos,int_glicose_sent_pos,int_alimentar_sent_pos,pneumatose_pos_count,piora_troca_gasosa_pos_count,fontanela_abaulada_pos_count,glicose_liquor_pos_count,prote_liquor_pos_count,leuco_liquor_pos_count,bacteria_liquor_pos_count,irritabilidade_pos_count,cultura_liquor_pos_count,hipoativ_pos_count,dren_serosa_pos_count,necrose_intestinal_pos_count,intestino_fixo_pos_count,sangue_fezes_pos_count,convulsao_pos_count,pneumoperitonio_pos_count,dist_abdominal_pos_count,asp_bilioso_pos_count,pcr_pos_count,letargia_pos_count,int_glicose_pos_count,int_alimentar_pos_count,pneumatose,piora_troca_gasosa,fontanela_abaulada,glicose_liquor,prote_liquor,leuco_liquor,bacteria_liquor,irritabilidade,cultura_liquor,hipoativ,dren_serosa,necrose_intestinal,intestino_fixo,sangue_fezes,convulsao,pneumoperitonio,dist_abdominal,asp_bilioso,pcr,letargia,int_glicose,int_alimentar,los_dia_parsed,CLINICA_INTERNACAO_CLINICA,CLINICA_INTERNACAO_OBSTETRICA,CLINICA_INTERNACAO_CIRURGIA,CLINICA_INTERNACAO_PSIQUIATRIA,CLINICA_INTERNACAO_CLINICA ONCOLOGIA,CLINICA_INTERNACAO_CIRURGIA ONCOLOGICA,CLINICA_INTERNACAO_PEDIATRIA,ESPECIALIDADE_INTERNACAO_Clínica,ESPECIALIDADE_INTERNACAO_Cirúgica,ESPECIALIDADE_INTERNACAO_Medicina intensiva,ESPECIALIDADE_INTERNACAO_Outros,ESPECIALIDADE_INTERNACAO_Ginecologia obstetricia,UNIDADE_INTERNACAO_Clínico,UNIDADE_INTERNACAO_Cirúrgico,UNIDADE_INTERNACAO_Clínico e Cirúrgico,UNIDADE_INTERNACAO_Emergência,UNIDADE_INTERNACAO_Outros,UNIDADE_INTERNACAO_UTI,UNIDADE_INTERNACAO_Obstetrícia,UNIDADE_INTERNACAO_Pediatria,UNIDADE_INTERNACAO_Gineco-obstetrícia,UNIDADE_inicio_janela_Clínico,UNIDADE_inicio_janela_Cirúrgico,UNIDADE_inicio_janela_Clínico e Cirúrgico,UNIDADE_inicio_janela_Emergência,UNIDADE_inicio_janela_Outros,UNIDADE_inicio_janela_UTI,UNIDADE_inicio_janela_Obstetrícia,UNIDADE_inicio_janela_Pediatria,UNIDADE_inicio_janela_Gineco-obstetrícia,UNIDADE_fim_janela_Clínico,UNIDADE_fim_janela_Cirúrgico,UNIDADE_fim_janela_Clínico e Cirúrgico,UNIDADE_fim_janela_Emergência,UNIDADE_fim_janela_Outros,UNIDADE_fim_janela_UTI,UNIDADE_fim_janela_Obstetrícia,UNIDADE_fim_janela_Pediatria,UNIDADE_fim_janela_Gineco-obstetrícia
0,False,False,False,False,False,False,False,False,False,False,False,2487,2023-05-24,1,20,9 INTERNACAO 08 ANDAR - BL 2BLII APTO 852 - 8º...,CLINICA,EMERGENCIA,CLINICA,2023-05-24 09:23:00,2023-05-26 18:03:00,0.0,0.0,280.0,4.0,18.0,0.782609,5.0,0.217391,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,50.0,60.0,0.0,0.0,0.0,4.0,55.250000,4.272002,-7.0,18.0,18.0,0.0,3.0,18.000000,0.000000,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,97.0,99.0,4.0,97.750000,0.957427,0.0,50.0,68.0,3.0,61.000000,9.643651,-18.0,114.0,114.0,1.0,114.0,NaN,0.0,36.2,37.0,0.0,0.0,0.0,4.0,36.425,0.386221,-0.7,71.0,128.0,4.0,106.250000,25.395210,50.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,23.0,INTERNACAO 08 ANDAR - BL 2,INTERNACAO 08 ANDAR - BL 2,3.0,12.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0,0,0,0,0,0,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,False,False,False,False,False,False,False,False,False,False,False,2487,2023-05-25,1,20,9 INTERNACAO 08 ANDAR - BL 2BLII APTO 852 - 8º...,CLINICA,EMERGENCIA,CLINICA,2023-05-24 09:23:00,2023-05-26 18:03:00,1.0,24.0,280.0,4.0,42.0,1.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,44.0,61.0,1.0,0.0,1.0,7.0,50.857143,5.209881,-1.0,12.0,20.0,0.0,7.0,15.714286,3.039424,1.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,95.0,99.0,7.0,97.571429,1.397276,-2.0,59.0,92.0,7.0,76.857143,13.752922,-2.0,NaN,NaN,0.0,NaN,NaN,NaN,36.0,36.4,0.0,0.0,0.0,7.0,36.200,0.173205,-0.4,102.0,140.0,7.0,121.142857,14.040757,-9.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,42.0,INTERNACAO 08 ANDAR - BL 2,INTERNACAO 08 ANDAR - BL 2,3.0,12.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0,0,0,0,0,0,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [4]:
df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 29292 entries, 0 to 29291
Columns: 712 entries, caso infeccao to UNIDADE_fim_janela_Gineco-obstetrícia
dtypes: bool(2), datetime64[us](3), float64(183), int64(52), object(9), str(463)
memory usage: 501.8 MB

In [5]:
df.memory_usage(deep=True)

Index                                                   132
caso infeccao                                         29292
caso infeccao hospitalar                              29292
Conjuntivite                                         770760
Infecção da cavidade oral                            770760
Infecção de pele                                     770760
Meningite                                            770760
comunitaria                                          770760
enterocolite                                         770760
ipcs                                                 770760
isc                                                  770760
pav                                                  770760
REGISTRO                                             234336
DIA_parsed                                           234336
SEXO                                                1464600
IDADE                                                234336
UNIDADE_INTERNACAO                                  2566945
ESPECIALIDADE_INTERNACAO                            1712521
TIPO_INTERNACAO                                     1718880
CLINICA_INTERNACAO                                  1712521
dthr_internacao                                      234336
dthr_alta                                            234336
los_dias                                             234336
los_horas                                            234336
CIRURGIA_tempo_total                                 234336
CIRURGIA_procedimentos_total                         234336
TECNICO(A) EM ENFERMAGEM_count                       234336
TECNICO(A) EM ENFERMAGEM_avg                         234336
ENFERMEIRO(A)_count                                  234336
ENFERMEIRO(A)_avg                                    234336
AUXILIAR DE ENFERMAGEM_count                         234336
AUXILIAR DE ENFERMAGEM_avg                           234336
ACADEMICODE ENFERMAGEM_count                         234336
ACADEMICO DE ENFERMAGEM_avg                          234336
MEDICO_count                                         234336
MEDICO_avg                                           234336
FISIOTERAPEUTA_count                                 234336
FISIOTERAPEUTA_avg                                   234336
OUTROS_count                                         234336
OUTROS_avg                                           234336
DIUR_min                                             234336
DIUR_max                                             234336
DIUR_count                                           234336
DIUR_avg                                             234336
DIUR_stddev                                          234336
DIUR_delta                                           234336
FC_min                                               234336
FC_max                                               234336
FC_ALTERADA                                          234336
FC_ALTA                                              234336
FC_BAIXA                                             234336
FC_count                                             234336
FC_avg                                               234336
FC_stddev                                            234336
FC_delta                                             234336
FR_min                                               234336
FR_max                                               234336
FR_ALTERADA                                          234336
FR_count                                             234336
FR_avg                                               234336
FR_stddev                                            234336
FR_delta                                             234336
HGT_min                                              234336
HGT_max                                              234336
HGT_ALTERADO                                         234336
HGT_count                                            234336
HGT_avg                                              234336
HGT_stddev                                           234336
HGT_delta                                            234336
OXIMETRIA_min                                        234336
OXIMETRIA_max                                        234336
OXIMETRIA_count                                      234336
OXIMETRIA_avg                                        234336
OXIMETRIA_stddev                                     234336
OXIMETRIA_delta                                      234336
PAD_min                                              234336
PAD_max                                              234336
PAD_count                                            234336
PAD_avg                                              234336
PAD_stddev                                           234336
PAD_delta                                            234336
PAS_min                                              234336
PAS_max                                              234336
PAS_count                                            234336
PAS_avg                                              234336
PAS_stddev                                           234336
PAS_delta                                            234336
TEMP_min                                             234336
TEMP_max                                             234336
TEMP_ALTERADA                                        234336
TEMP_ALTA                                            234336
TEMP_BAIXA                                           234336
TEMP_count                                           234336
TEMP_avg                                             234336
TEMP_stddev                                          234336
TEMP_delta                                           234336
PA_min                                               234336
PA_max                                               234336
PA_count                                             234336
PA_avg                                               234336
PA_stddev                                            234336
PA_delta                                             234336
PAM_min                                              234336
PAM_max                                              234336
PAM_count                                            234336
PAM_avg                                              234336
PAM_stddev                                           234336
PAM_delta                                            234336
O2_min                                               234336
O2_max                                               234336
O2_count                                             234336
O2_avg                                               234336
O2_stddev                                            234336
O2_delta                                             234336
FIO2_min                                             234336
FIO2_max                                             234336
FIO2_count                                           234336
FIO2_avg                                             234336
FIO2_stddev                                          234336
FIO2_delta                                           234336
PEEP_min                                             234336
PEEP_max                                             234336
PEEP_count                                           234336
PEEP_avg                                             234336
PEEP_stddev                                          234336
PEEP_delta                                           234336
SINAIS_VITAIS_registros_total                        234336
UNIDADE_fim_janela                                   955532
UNIDADE_inicio_janela                                957042
UNIDADE_movimento_total                              234336
EVOLUCAO_notas_total                                 234336
EVOLUCAO_notas_total_dia                             234336
aciclovir_count                                      234336
amoxicilina_sulbactam_count                          234336
cefadroxila_count                                    234336
cefalotina_count                                     234336
cefotaxima_count                                     234336
ceftazidima_count                                    234336
ceftazidima_avibactam_count                          234336
ceftalozana_tazobactam_count                         234336
cetoconazol_count                                    234336
claritromicina_count                                 234336
cloranfenicol_count                                  234336
doxiciclina_count                                    234336
ertapenem_count                                      234336
eritromicina_count                                   234336
ganciclovir_count                                    234336
ivermectina_count                                    234336
micafungina_count                                    234336
miconazol_count                                      234336
moxifloxacino_count                                  234336
mupirocina_count                                     234336
neomicina_count                                      234336
rifampicina_count                                    234336
sulfadiazina_count                                   234336
teicoplanina_count                                   234336
voriconazol_count                                    234336
ciprofloxacino_count                                 234336
outro_count                                          234336
amicacina_count                                      234336
amoxicilina_clavulanato_count                        234336
amoxicilina_count                                    234336
ampicilina_count                                     234336
azitromicina_count                                   234336
penicilinagbenzatina_count                           234336
penicilinagpotassica_count                           234336
cefalexina_count                                     234336
cefazolina_count                                     234336
cefepima_count                                       234336
ceftriaxona_count                                    234336
cefuroxima_count                                     234336
clindamicina_count                                   234336
fluconazol_count                                     234336
gentamicina_count                                    234336
levofloxacino_count                                  234336
linezolida_count                                     234336
meropenem_count                                      234336
metronidazol_count                                   234336
nistatina_count                                      234336
oxacilina_count                                      234336
piperacilina_tazobactam_count                        234336
ampicilina_sulbactam_count                           234336
sulfametoxazol_trimetoprim_count                     234336
polimixinab_count                                    234336
tobramicina_count                                    234336
vancomicina_count                                    234336
via_topico_count                                     234336
via_sng_count                                        234336
via_outro_count                                      234336
via_ev_count                                         234336
via_im_count                                         234336
via_vo_count                                         234336
agg_hemocultura                                      941454
qtd_hemocultura_positiva                             234336
qtd_hemocultura_sem_crescimento                      234336
qtd_cultura_positiva                                 234336
qtd_cultura_sem_crescimento                          234336
qtd_bacteroscopico_positiva                          234336
qtd_bacteroscopico_negativa                          234336
agg_urocultura                                       937641
qtd_urocultura_positiva                              234336
qtd_urocultura_sem_crescimento                       234336
qtd_bacteriologico_positiva                          234336
qtd_bacteriologico_sem_crescimento                   234336
leuco_min                                            234336
leuco_max                                            234336
leuco_avg                                            234336
rdw_min                                              234336
rdw_max                                              234336
rdw_avg                                              234336
neuto_min                                            234336
neuto_max                                            234336
neuto_avg                                            234336
LEUCO_ALTERADO                                       234336
LEUCO_ALTO                                           234336
LEUCO_BAIXO                                          234336
RDW_ALTO                                             234336
NEUTROFILO_ALTO                                      234336
RAGIOLOGIA_laudos_total                              234336
tosse                                                981864
ronco                                                981864
cavita                                               981864
opac                                                 981864
infil                                                981864
fibrose_cistica                                      981864
sec_pur_pulmonar                                     981864
secr                                                 981864
puru                                                 981864
secr_traq                                            981864
o2                                                   981864
dpoc                                                 981864
hemoptise                                            981864
leucemia                                             981864
esplenectomia                                        981864
febre                                                981864
consol                                               981864
linfoma                                              981864
acinetobacter                                        981864
amarelada                                            981864
aspiracao                                            981864
broncograma_aereo                                    981864
crepitante                                           981864
enterobacter                                         981864
enterococcus                                         981864
hemophylus                                           981864
hipertermia                                          981864
imunossuprimido                                      981864
infeccao                                             981864
klebsiella                                           981864
legionella                                           981864
leucocitose                                          981864
leucopenia                                           981864
moraxella                                            981864
pneumococcus                                         981864
pseudomonas                                          981864
sibilos                                              981864
intubacao                                            981864
staphylococcus_aureus                                981864
sepse_pulmonar                                       981864
sepse_respiratoria                                   981864
sepse_urinaria                                       981864
padrao_ventilatorio                                  981864
insuficiencia_ventilatoria                           981864
esforco_ventilatorio                                 981864
lavado_broncoalveolar                                981864
derrame_pleural                                      981864
escherichia_coli                                     981864
choque_septico                                       981864
dor_pleuritica                                       981864
dor_ventilatorio_dependente                          981864
ventilacao_mecanica                                  981864
iot                                                  981864
pav                                                  981864
endoftalmite                                         981864
eritema                                              981864
hiperemia                                            981864
mediastinite                                         981864
staphylococcus_coagulase_negativo                    981864
supuracao                                            981864
rubor                                                981864
mal_estar                                            981864
abscesso                                             981864
calor                                                981864
dreno                                                981864
edema                                                981864
endocardite                                          981864
antibiotico                                          981864
bacteriologico                                       981864
deiscencia                                           981864
resistente                                           981864
taquicardia                                          981864
cateter                                              981864
cateter_arterial                                     981864
cateter_urinario                                     981864
cvc                                                  981864
cateter_venoso_periferico                            981864
clorose                                              981864
instabilidade                                        981864
oliguria                                             981864
hipotensao                                           981864
anuria                                               981864
bacteremia                                           981864
bacteriuria                                          981864
disuria                                              981864
leucocituria                                         981864
nitrito                                              981864
svd                                                  981864
tsa                                                  981864
choque                                               981864
staphylococcus                                       981864
e_coli                                               981864
colecao                                              981864
tremor                                               981864
calafrio                                             981864
pos_operatorio                                       981864
dor_suprapubica                                      981864
foco_urinario                                        981864
colite_pseudomembranosa                              981864
yersinia                                             981864
vomito                                               981864
shigella                                             981864
salmonela                                            981864
nausea                                               981864
giardia                                              981864
dor_cabeca                                           981864
dor_abdominal                                        981864
diarreia                                             981864
clostridium                                          981864
campylobacter                                        981864
urgencia_urinaria                                    981864
urgencia_miccional                                   981864
sondagem_alivio                                      981864
sondagem_vesical                                     981864

### Export de dataset

In [ ]:
# df.to_feather("dataset_novos_criterios_neo_completo")

## Organização de variáveis

In [11]:
# Dado controle - quem é e de quando é
dados_controle = ["REGISTRO", "DIA_parsed", "dthr_internacao", "dthr_alta"]

# Dado texto: 
dado_categoricos = ["UNIDADE_INTERNACAO", "ESPECIALIDADE_INTERNACAO", "TIPO_INTERNACAO", "CLINICA_INTERNACAO", "SEXO", "TEMP_INCUBADORA_min", "TEMP_INCUBADORA_max", "TEMP_INCUBADORA_count", "TEMP_INCUBADORA_avg", "TEMP_INCUBADORA_stddev", "TEMP_INCUBADORA_delta", "UNIDADE_fim_janela", "UNIDADE_inicio_janela", "agg_hemocultura", "agg_urocultura"]

# Gabaritos
gabaritos = ["caso_infeccao", "pnm", "isc", "itu", "pav", "ipcs", "traqueobronquite"]
gabaritos = ['caso infeccao', 'caso infeccao hospitalar', 'Conjuntivite', 'Infecção da cavidade oral', 'Infecção de pele', 'Meningite', 'comunitaria', 'enterocolite', 'ipcs', 'isc', 'pav']

# Features
features_atendimento = ["IDADE", "los_dias", "los_horas"]

features_cirurgias = ["CIRURGIA_tempo_total", "CIRURGIA_procedimentos_total"]

# Sinais vitais
features_sinal_vital = ["TECNICO(A) EM ENFERMAGEM_count", "TECNICO(A) EM ENFERMAGEM_avg", "ENFERMEIRO(A)_count", "ENFERMEIRO(A)_avg", "AUXILIAR DE ENFERMAGEM_count", "AUXILIAR DE ENFERMAGEM_avg", "ACADEMICODE ENFERMAGEM_count", "ACADEMICO DE ENFERMAGEM_avg", "MEDICO_count", "MEDICO_avg", "FISIOTERAPEUTA_count", "FISIOTERAPEUTA_avg", "OUTROS_count", "OUTROS_avg", "DIUR_min", "DIUR_max", "DIUR_count", "DIUR_avg", "DIUR_stddev", "DIUR_delta", "FC_min", "FC_max", "FC_ALTERADA", "FC_ALTA", "FC_BAIXA", "FC_count", "FC_avg", "FC_stddev", "FC_delta", "FR_min", "FR_max", "FR_ALTERADO", "FR_count", "FR_avg", "FR_stddev", "FR_delta", "HGT_min", "HGT_max", "HGT_ALTERADO", "HGT_count", "HGT_avg", "HGT_stddev", "HGT_delta", "OXIMETRIA_min", "OXIMETRIA_max", "OXIMETRIA_count", "OXIMETRIA_avg", "OXIMETRIA_stddev", "OXIMETRIA_delta", "PAD_min", "PAD_max", "PAD_count", "PAD_avg", "PAD_stddev", "PAD_delta", "PAS_min", "PAS_max", "PAS_count", "PAS_avg", "PAS_stddev", "PAS_delta", "TEMP_min", "TEMP_max", "TEMP_ALTERADA", "TEMP_ALTA", "TEMP_BAIXA", "TEMP_count", "TEMP_avg", "TEMP_stddev", "TEMP_delta", "PA_min", "PA_max", "PA_count", "PA_avg", "PA_stddev", "PA_delta", "PAM_min", "PAM_max", "PAM_count", "PAM_avg", "PAM_stddev", "PAM_delta", "O2_min", "O2_max", "O2_count", "O2_avg", "O2_stddev", "O2_delta", "FIO2_min", "FIO2_max", "FIO2_count", "FIO2_avg", "FIO2_stddev", "FIO2_delta", "PEEP_min", "PEEP_max", "PEEP_count", "PEEP_avg", "PEEP_stddev", "PEEP_delta", "SINAIS_VITAIS_registros_total"]

# Volumetrico evos e movimentacao
features_evol = ["UNIDADE_movimento_total", "EVOLUCAO_notas_total", "EVOLUCAO_notas_total_dia"]

# Antibioticos utilizados
features_atb = ["aciclovir_count", "amoxicilina_sulbactam_count", "cefadroxila_count", "cefalotina_count", "cefotaxima_count", "ceftazidima_count", "ceftazidima_avibactam_count", "ceftalozana_tazobactam_count", "cetoconazol_count", "claritromicina_count", "cloranfenicol_count", "doxiciclina_count", "ertapenem_count", "eritromicina_count", "ganciclovir_count", "ivermectina_count", "micafungina_count", "miconazol_count", "moxifloxacino_count", "mupirocina_count", "neomicina_count", "rifampicina_count", "sulfadiazina_count", "teicoplanina_count", "voriconazol_count", "ciprofloxacino_count", "outro_count", "amicacina_count", "amoxicilina_clavulanato_count", "amoxicilina_count", "ampicilina_count", "azitromicina_count", "penicilinagbenzatina_count", "penicilinagpotassica_count", "cefalexina_count", "cefazolina_count", "cefepima_count", "ceftriaxona_count", "cefuroxima_count", "clindamicina_count", "fluconazol_count", "gentamicina_count", "levofloxacino_count", "linezolida_count", "meropenem_count", "metronidazol_count", "nistatina_count", "oxacilina_count", "piperacilina_tazobactam_count", "ampicilina_sulbactam_count", "sulfametoxazol_trimetoprim_count", "polimixinab_count", "tobramicina_count", "vancomicina_count", "via_topico_count", "via_sng_count", "via_outro_count", "via_ev_count", "via_im_count", "via_vo_count"]

# Dados de exame
# Culturais
features_culturais = ["qtd_hemocultura_positiva", "qtd_hemocultura_sem_crescimento", "qtd_cultura_positiva", "qtd_cultura_sem_crescimento", "qtd_bacteroscopico_positiva", "qtd_bacteroscopico_negativa", "qtd_urocultura_positiva", "qtd_urocultura_sem_crescimento", "qtd_bacteriologico_positiva", "qtd_bacteriologico_sem_crescimento"]

# Sangue
features_sangue = ["leuco_min", "leuco_max", "leuco_avg", "rdw_min", "rdw_max", "rdw_avg", "neuto_min", "neuto_max", "neuto_avg", "LEUCO_ALTERADO", "LEUCO_ALTO", "LEUCO_BAIXO", "RDW_ALTO", "NEUTROFILO_ALTO"]

# Laudos Imagem
features_laudos_imagem = ["RAGIOLOGIA_laudos_total"]

# Proporção de termos no texto 
features_proporcao_texto = ["tosse", "ronco", "cavita", "opac", "infil", "fibrose_cistica", "sec_pur_pulmonar", "secr", "puru", "secr_traq", "o2", "hemoptise", "leucemia", "esplenectomia", "febre", "consol", "linfoma", "acinetobacter", "amarelada", "aspiracao", "crepitante", "enterobacter", "enterococcus", "hemophylus", "hipertermia", "imunossuprimido", "infeccao", "klebsiella", "leucocitose", "leucopenia", "moraxella", "pneumococcus", "pseudomonas", "sibilos", "intubacao", "staphylococcus_aureus", "sepse_pulmonar", "sepse_respiratoria", "sepse_urinaria", "padrao_ventilatorio", "insuficiencia_ventilatoria", "esforco_ventilatorio", "lavado_broncoalveolar", "derrame_pleural", "escherichia_coli", "choque_septico", "dor_pleuritica", "dor_ventilatorio_dependente", "ventilacao_mecanica", "iot", 
                            # "pav_1",
                            "eritema", "hiperemia", "mediastinite", "staphylococcus_coagulase_negativo", "supuracao", "rubor", "mal_estar", "abscesso", "calor", "dreno", "edema", "endocardite", "antibiotico", "bacteriologico", "deiscencia", "resistente", "taquicardia", "cateter", "cateter_arterial", "cateter_urinario", "cvc", "cateter_venoso_periferico", "instabilidade", "oliguria", "hipotensao", "anuria", "bacteremia", "bacteriuria", "disuria", "leucocituria", "nitrito", "svd", "tsa", "choque", "staphylococcus", "e_coli", "colecao", "tremor", "calafrio", "pos_operatorio", "dor_suprapubica", "foco_urinario", "colite_pseudomembranosa", "vomito", "shigella", "salmonela", "nausea", "dor_cabeca", "dor_abdominal", "diarreia", "clostridium", "urgencia_urinaria", "urgencia_miccional", "sondagem_alivio", "sondagem_vesical", "urocultura", "piuria", "albumina", "press_parc_co2", "creatinina", "glicose", "plaquetas", "bilirrubina", "cardiomegalia", "lesao_pulmonar", "pneumonia", "atelectasia", "pneumotorax", "fratura", "freq_respiratoria", "freq_cardiaca", "pressao_sanguinea", "saturacao_sangue", "hemocultura", "temperatura", "sibilancia", "hipotermia", "apneia", "bradicardia", "streptococcus_viridans", "consciencia", "hcm", "hgm", "covid", "peep", "fio2", "spo2", "sne", "desnutricao", "sedacao", "vsg", "fosfatase_alcalina", "ldh", "cetamina", "propofol", "clorpromazina", "fentanil", "pancuronio", "noradrenalina", "diazepan", "lorazepan", "flumazenil", "clonidina", "npt", "cateter_monolumen", "cateter_duplolumen", "cateter_triplolumen", "portocath", "cateter_hickmann", "shilley", "obesidade", "diabetes", "neutropenia"]

# contagem de termos em texto
features_contagem_texto = ["tosse_pos_count", "ronco_pos_count", "cavita_pos_count", "opac_pos_count", "infil_pos_count", "fibrose_cistica_pos_count", "sec_pur_pulmonar_pos_count", "secr_pos_count", "puru_pos_count", "secr_traq_pos_count", "o2_pos_count", "hemoptise_pos_count", "leucemia_pos_count", "esplenectomia_pos_count", "febre_pos_count", "consol_pos_count", "linfoma_pos_count", "acinetobacter_pos_count", "amarelada_pos_count", "aspiracao_pos_count", "crepitante_pos_count", "enterobacter_pos_count", "enterococcus_pos_count", "hemophylus_pos_count", "hipertermia_pos_count", "imunossuprimido_pos_count", "infeccao_pos_count", "klebsiella_pos_count", "leucocitose_pos_count", "leucopenia_pos_count", "moraxella_pos_count", "pneumococcus_pos_count", "pseudomonas_pos_count", "sibilos_pos_count", "intubacao_pos_count", "staphylococcus_aureus_pos_count", "sepse_pulmonar_pos_count", "sepse_respiratoria_pos_count", "sepse_urinaria_pos_count", "padrao_ventilatorio_pos_count", "insuficiencia_ventilatoria_pos_count", "esforco_ventilatorio_pos_count", "lavado_broncoalveolar_pos_count", "derrame_pleural_pos_count", "escherichia_coli_pos_count", "choque_septico_pos_count", "dor_pleuritica_pos_count", "dor_ventilatorio_dependente_pos_count", "ventilacao_mecanica_pos_count", "iot_pos_count", "pav_pos_count", "eritema_pos_count", "hiperemia_pos_count", "mediastinite_pos_count", "staphylococcus_coagulase_negativo_pos_count", "supuracao_pos_count", "rubor_pos_count", "mal_estar_pos_count", "abscesso_pos_count", "calor_pos_count", "dreno_pos_count", "edema_pos_count", "endocardite_pos_count", "antibiotico_pos_count", "bacteriologico_pos_count", "deiscencia_pos_count", "resistente_pos_count", "taquicardia_pos_count", "cateter_pos_count", "cateter_arterial_pos_count", "cateter_urinario_pos_count", "cvc_pos_count", "cateter_venoso_periferico_pos_count", "instabilidade_pos_count", "oliguria_pos_count", "hipotensao_pos_count", "anuria_pos_count", "bacteremia_pos_count", "bacteriuria_pos_count", "disuria_pos_count", "leucocituria_pos_count", "nitrito_pos_count", "svd_pos_count", "tsa_pos_count", "choque_pos_count", "staphylococcus_pos_count", "e_coli_pos_count", "colecao_pos_count", "tremor_pos_count", "calafrio_pos_count", "pos_operatorio_pos_count", "dor_suprapubica_pos_count", "foco_urinario_pos_count", "colite_pseudomembranosa_pos_count", "vomito_pos_count", "shigella_pos_count", "salmonela_pos_count", "nausea_pos_count", "dor_cabeca_pos_count", "dor_abdominal_pos_count", "diarreia_pos_count", "clostridium_pos_count", "urgencia_urinaria_pos_count", "urgencia_miccional_pos_count", "sondagem_alivio_pos_count", "sondagem_vesical_pos_count", "urocultura_pos_count", "piuria_pos_count", "albumina_pos_count", "press_parc_co2_pos_count", "creatinina_pos_count", "glicose_pos_count", "plaquetas_pos_count", "bilirrubina_pos_count", "cardiomegalia_pos_count", "lesao_pulmonar_pos_count", "pneumonia_pos_count", "atelectasia_pos_count", "pneumotorax_pos_count", "fratura_pos_count", "freq_respiratoria_pos_count", "freq_cardiaca_pos_count", "pressao_sanguinea_pos_count", "saturacao_sangue_pos_count", "hemocultura_pos_count", "temperatura_pos_count", "sibilancia_pos_count", "hipotermia_pos_count", "apneia_pos_count", "bradicardia_pos_count", "streptococcus_viridans_pos_count", "consciencia_pos_count", "hcm_pos_count", "hgm_pos_count", "covid_pos_count", "peep_pos_count", "fio2_pos_count", "spo2_pos_count", "sne_pos_count", "desnutricao_pos_count", "sedacao_pos_count", "vsg_pos_count", "fosfatase_alcalina_pos_count", "ldh_pos_count", "cetamina_pos_count", "propofol_pos_count", "clorpromazina_pos_count", "fentanil_pos_count", "pancuronio_pos_count", "noradrenalina_pos_count", "diazepan_pos_count", "lorazepan_pos_count", "flumazenil_pos_count", "clonidina_pos_count", "npt_pos_count", "cateter_monolumen_pos_count", "cateter_duplolumen_pos_count", "cateter_triplolumen_pos_count", "portocath_pos_count", "cateter_hickmann_pos_count", "shilley_pos_count", "obesidade_pos_count", "diabetes_pos_count", "neutropenia_pos_count"]

#Critérios adultos que a Stephani tirou
features_adulto_antigo = ["endoftalmite", "propionibacterium", "avc", "cryptococcus", "bicarbonato", "pneumocystis", "corynecterium", "broncograma_aereo", "calcio", "histoplasma", "bacillus", "yersinia", "paracoccidioides", "aerococcus", "bacteroides", "clorose", "coccidioides", "hemoglobina", "candida", "veilonella", "potassio", "fusobacterium", "giardia", "sodio", "peptostreptococcus", "dpoc", "legionella", "tabagismo", "campylobacter", "ph_sangue"]

# Proporção de termos no texto - novos critérios
features_proporcao_texto_novos = ["pneumatose", "piora_troca_gasosa", "fontanela_abaulada", "glicose_liquor", "prote_liquor", "leuco_liquor", "bacteria_liquor", "irritabilidade", "cultura_liquor", "hipoativ", "dren_serosa", "necrose_intestinal", "intestino_fixo", "sangue_fezes", "convulsao", "pneumoperitonio", "dist_abdominal", "asp_bilioso", "pcr","letargia", "int_glicose", "int_alimentar"]
        
# contagem de termos em texto - novos critérios
features_contagem_texto_novos = ["pneumatose_pos_count", "piora_troca_gasosa_pos_count", "fontanela_abaulada_pos_count", "glicose_liquor_pos_count", "prote_liquor_pos_count", "leuco_liquor_pos_count", "bacteria_liquor_pos_count", "irritabilidade_pos_count", "cultura_liquor_pos_count", "hipoativ_pos_count", "dren_serosa_pos_count", "necrose_intestinal_pos_count", "intestino_fixo_pos_count", "sangue_fezes_pos_count", "convulsao_pos_count", "pneumoperitonio_pos_count", "dist_abdominal_pos_count", "asp_bilioso_pos_count", "pcr_pos_count","letargia_pos_count", "int_glicose_pos_count", "int_alimentar_pos_count"]

### Gabarito

In [12]:
df_texto_gabarito = df[gabaritos+features_culturais+features_sangue+features_proporcao_texto+features_proporcao_texto_novos]
df_texto_gabarito.head()

,caso infeccao,caso infeccao hospitalar,Conjuntivite,Infecção da cavidade oral,Infecção de pele,Meningite,comunitaria,enterocolite,ipcs,isc,pav,pav,qtd_hemocultura_positiva,qtd_hemocultura_sem_crescimento,qtd_cultura_positiva,qtd_cultura_sem_crescimento,qtd_bacteroscopico_positiva,qtd_bacteroscopico_negativa,qtd_urocultura_positiva,qtd_urocultura_sem_crescimento,qtd_bacteriologico_positiva,qtd_bacteriologico_sem_crescimento,leuco_min,leuco_max,leuco_avg,rdw_min,rdw_max,rdw_avg,neuto_min,neuto_max,neuto_avg,LEUCO_ALTERADO,LEUCO_ALTO,LEUCO_BAIXO,RDW_ALTO,NEUTROFILO_ALTO,tosse,ronco,cavita,opac,infil,fibrose_cistica,sec_pur_pulmonar,secr,puru,secr_traq,o2,hemoptise,leucemia,esplenectomia,febre,consol,linfoma,acinetobacter,amarelada,aspiracao,crepitante,enterobacter,enterococcus,hemophylus,hipertermia,imunossuprimido,infeccao,klebsiella,leucocitose,leucopenia,moraxella,pneumococcus,pseudomonas,sibilos,intubacao,staphylococcus_aureus,sepse_pulmonar,sepse_respiratoria,sepse_urinaria,padrao_ventilatorio,insuficiencia_ventilatoria,esforco_ventilatorio,lavado_broncoalveolar,derrame_pleural,escherichia_coli,choque_septico,dor_pleuritica,dor_ventilatorio_dependente,ventilacao_mecanica,iot,eritema,hiperemia,mediastinite,staphylococcus_coagulase_negativo,supuracao,rubor,mal_estar,abscesso,calor,dreno,edema,endocardite,antibiotico,bacteriologico,deiscencia,resistente,taquicardia,cateter,cateter_arterial,cateter_urinario,cvc,cateter_venoso_periferico,instabilidade,oliguria,hipotensao,anuria,bacteremia,bacteriuria,disuria,leucocituria,nitrito,svd,tsa,choque,staphylococcus,e_coli,colecao,tremor,calafrio,pos_operatorio,dor_suprapubica,foco_urinario,colite_pseudomembranosa,vomito,shigella,salmonela,nausea,dor_cabeca,dor_abdominal,diarreia,clostridium,urgencia_urinaria,urgencia_miccional,sondagem_alivio,sondagem_vesical,urocultura,piuria,albumina,press_parc_co2,creatinina,glicose,plaquetas,bilirrubina,cardiomegalia,lesao_pulmonar,pneumonia,atelectasia,pneumotorax,fratura,freq_respiratoria,freq_cardiaca,pressao_sanguinea,saturacao_sangue,hemocultura,temperatura,sibilancia,hipotermia,apneia,bradicardia,streptococcus_viridans,consciencia,hcm,hgm,covid,peep,fio2,spo2,sne,desnutricao,sedacao,vsg,fosfatase_alcalina,ldh,cetamina,propofol,clorpromazina,fentanil,pancuronio,noradrenalina,diazepan,lorazepan,flumazenil,clonidina,npt,cateter_monolumen,cateter_duplolumen,cateter_triplolumen,portocath,cateter_hickmann,shilley,obesidade,diabetes,neutropenia,pneumatose,piora_troca_gasosa,fontanela_abaulada,glicose_liquor,prote_liquor,leuco_liquor,bacteria_liquor,irritabilidade,cultura_liquor,hipoativ,dren_serosa,necrose_intestinal,intestino_fixo,sangue_fezes,convulsao,pneumoperitonio,dist_abdominal,asp_bilioso,pcr,letargia,int_glicose,int_alimentar
0,False,False,False,False,False,False,False,False,False,False,False,NaN,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,False,False,False,False,False,False,False,False,False,False,False,NaN,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,False,False,False,False,False,False,False,False,False,False,False,NaN,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,False,False,False,False,False,False,False,False,False,False,False,NaN,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,True,False,False,False,False,False,True,False,False,False,False,NaN,0,0,1,0,0,0,1,0,0,0,5370.0,5370.0,5370.0,13.5,13.5,13.5,2680.0,2680.0,2680.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Variáveis usadas - texto + exames + laudos

In [25]:
X_texto = df_texto_gabarito.drop(columns= gabaritos)
y_texto = df_texto_gabarito['caso infeccao']
X_texto_train, X_texto_test, y_texto_train, y_texto_test = train_test_split(X_texto, y_texto, test_size=0.2, random_state=42, stratify= y_texto)
len(X_texto_train), len(X_texto_test), len(y_texto_train), len(y_texto_test)

(23433, 5859, 23433, 5859)

# Data Exploring

## Split dataset

In [26]:
# X = df.drop(columns= ['REGISTRO', 'los_horas', 'caso_infeccao', 'pnm', 'isc', 'itu', 'pav', 'ipcs', 'traqueobronquite', 'DIA_parsed', 'SEXO', 'UNIDADE_INTERNACAO', 'UNIDADE_INTERNACAO', 'ESPECIALIDADE_INTERNACAO', 'TIPO_INTERNACAO',	'CLINICA_INTERNACAO', 'dthr_internacao', 'dthr_alta', 'UNIDADE_fim_janela', 'UNIDADE_inicio_janela', 'agg_hemocultura', 'agg_urocultura'])
X = df.drop(columns= gabaritos)
y = df['caso infeccao']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify= y)

## Decision Tree

### Best Estimator trial

In [20]:
#Modelo base
dt = DecisionTreeClassifier(random_state= 28)

# Grid de parâmetros para testar
param_grid = {
    'criterion': ['gini', 'entropy', 'log_loss'],            # medida de impureza
    'max_depth': list(range(10, 11)) + [None],        # profundidade máxima
    'min_samples_split': list(range(3, 20)),         # mín. amostras para dividir um nó
    'min_samples_leaf': list(range(2, 20)),            # mín. amostras em uma folha
    'max_features': [None],      # nº de features consideradas por vez
    'splitter': ['best', 'random'],
    'ccp_alpha': [0, 0.001, 0.002, 0.005, 0.01, 0.02],
    'class_weight': [None, "balanced"]
}

scorer = 'recall'

scoring_metrics = {
    'recall': 'recall',
    'precision': 'precision',
    'f1': 'f1',
    'roc_auc': 'roc_auc'
}

# GridSearch
grid = GridSearchCV(
    estimator=dt,
    param_grid=param_grid,
    cv=5,
    scoring=scoring_metrics,
    refit=scorer,
    n_jobs=-1,
    verbose=3,
    return_train_score=False
)

# Treinar o grid
grid.fit(X_train, y_train)

best_model = grid.best_estimator_
joblib.dump(best_model, 'melhor_modelo_recall_focado.pkl')

print(f"\nMelhor modelo salvo (Decidido pelo Recall).")
print(f"Melhores parâmetros: {grid.best_params_}")
# Note que agora o best_score_ se refere à métrica do refit
print(f"Melhor Recall: {grid.best_score_:.4f}")

# 5. Salvando o DataFrame Completo (Agora muito mais rico)
results_df = pd.DataFrame(grid.cv_results_)

# As colunas agora terão prefixos com os nomes das métricas
# Ex: mean_test_recall, mean_test_precision, mean_test_f1
cols_to_keep = [
    'params', 
    'mean_test_recall', 
    'mean_test_precision', 
    'mean_test_f1',
    'mean_test_roc_auc'
]

# Ordenando pelo Recall (ou a métrica que você preferir visualizar)
final_df = results_df[cols_to_keep].sort_values(by='mean_test_recall', ascending=False)

final_df.to_csv('grid_multimetric_results.csv', index=False)
print("CSV salvo com todas as métricas comparadas!")

final_df = results_df.sort_values(by='mean_test_recall', ascending=False)

final_df.to_csv('grid_multimetric_results_completo.csv', index=False)

Fitting 5 folds for each of 44064 candidates, totalling 220320 fits
[CV 1/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=3, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 2/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=3, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 3/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=3, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 4/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=3, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 5/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=3, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 1/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=3, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 2/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=3, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 3/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=3, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 4/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=3, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 5/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=3, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 1/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=4, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 2/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=4, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 3/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=4, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 4/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=4, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 5/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=4, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 1/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=4, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 2/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=4, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 3/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=4, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 4/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=4, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 5/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=4, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 1/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=5, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 2/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=5, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 3/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=5, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 4/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=5, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 5/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=5, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 1/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=5, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 2/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=5, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 3/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=5, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 4/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=5, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 5/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=5, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 3/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=6, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.4s
[CV 1/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=6, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.4s
[CV 4/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=6, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.4s
[CV 2/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=6, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 5/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=6, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 1/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=6, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 2/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=6, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 3/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=6, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 4/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=6, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.5s
[CV 5/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=6, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.4s
[CV 1/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=7, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 2/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=7, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 3/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=7, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 4/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=7, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 5/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=7, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 1/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=7, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 2/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=7, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 3/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=7, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 4/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=7, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 5/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=7, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 1/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=8, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 2/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=8, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.5s
[CV 3/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=8, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 4/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=8, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.4s
[CV 5/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=8, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 1/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=8, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 2/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=8, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 3/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=8, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 4/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=8, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.4s
[CV 5/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=8, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 1/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=9, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 2/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=9, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 3/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=9, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 4/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=9, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.4s
[CV 5/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=9, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 1/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=9, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 2/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=9, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 3/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=9, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 4/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=9, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 5/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=9, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 1/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=10, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 2/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=10, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 3/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=10, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 4/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=10, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s
[CV 5/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=10, splitter=best; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 1/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=10, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 2/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=10, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 3/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=10, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 4/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=10, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.2s
[CV 5/5] END ccp_alpha=0, class_weight=None, criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, min_samples_split=10, splitter=random; f1: (test=nan) precision: (test=nan) recall: (test=nan) roc_auc: (test=nan) total time=   0.3s

KeyboardInterrupt:

In [44]:
model = DecisionTreeClassifier(
    criterion='gini', 
    splitter='random', 
    random_state= 113, 
    min_samples_leaf= 4,
    min_samples_split= 4,
    max_features= None,
    max_depth= None,
    class_weight= 'balanced'# {0: 1, 1: 20}
)

model.fit(X_texto_train, y_texto_train)

DecisionTreeClassifier(class_weight='balanced', min_samples_leaf=4,
                       min_samples_split=4, random_state=113,
                       splitter='random')

In [45]:
y_train_pred = model.predict(X_texto_train)
acc = accuracy_score(y_train, y_train_pred)
print(f"Accurácia: {acc}")
cm = confusion_matrix(y_train, y_train_pred)
print(f"Confusion Matrix treino: \n{cm}\n")
report = classification_report(y_train, y_train_pred)
print(report)

print("\n=========================================================\n")
# Validando test
y_pred = model.predict(X_texto_test)
    
acc = accuracy_score(y_test, y_pred)
print(f"Accurácia: {acc}")
cm = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix teste: \n{cm}")
report = classification_report(y_test, y_pred)
print(report)

Accurácia: 0.9318482481969872
Confusion Matrix treino:
[[21522  1527]
 [   70   314]]

              precision    recall  f1-score   support

       False       1.00      0.93      0.96     23049
        True       0.17      0.82      0.28       384

    accuracy                           0.93     23433
   macro avg       0.58      0.88      0.62     23433
weighted avg       0.98      0.93      0.95     23433


=========================================================

Accurácia: 0.9300221880867042
Confusion Matrix teste:
[[5382  381]
 [  29   67]]
              precision    recall  f1-score   support

       False       0.99      0.93      0.96      5763
        True       0.15      0.70      0.25        96

    accuracy                           0.93      5859
   macro avg       0.57      0.82      0.60      5859
weighted avg       0.98      0.93      0.95      5859

## Analisando importância dos parâmetros

In [46]:
pd.options.display.float_format = '{:.4f}'.format
importances = pd.Series(model.feature_importances_, index=X_texto_test.columns)

# Ordena em ordem decrescente
importances = importances.sort_values(ascending=False)
print(importances)

importances = importances.to_dict()
importances['model'] = 'random_forest'

qtd_cultura_positiva                 0.3676
qtd_hemocultura_sem_crescimento      0.3480
qtd_cultura_sem_crescimento          0.1539
LEUCO_ALTERADO                       0.0358
neuto_min                            0.0154
leuco_avg                            0.0099
dreno                                0.0094
int_glicose                          0.0082
leuco_max                            0.0067
rdw_min                              0.0058
neuto_avg                            0.0052
leuco_min                            0.0051
sedacao                              0.0049
rdw_max                              0.0046
neuto_max                            0.0038
LEUCO_BAIXO                          0.0030
rdw_avg                              0.0029
qtd_urocultura_sem_crescimento       0.0025
RDW_ALTO                             0.0019
sangue_fezes                         0.0018
NEUTROFILO_ALTO                      0.0011
spo2                                 0.0010
qtd_urocultura_positiva              0.0006
diazepan                             0.0004
opac                                 0.0004
qtd_hemocultura_positiva             0.0000
consol                               0.0000
infil                                0.0000
iot                                  0.0000
aspiracao                            0.0000
fratura                              0.0000
cateter                              0.0000
pressao_sanguinea                    0.0000
LEUCO_ALTO                           0.0000
sec_pur_pulmonar                     0.0000
hemoptise                            0.0000
secr                                 0.0000
leucemia                             0.0000
esplenectomia                        0.0000
febre                                0.0000
secr_traq                            0.0000
puru                                 0.0000
qtd_bacteroscopico_positiva          0.0000
qtd_bacteroscopico_negativa          0.0000
qtd_bacteriologico_positiva          0.0000
qtd_bacteriologico_sem_crescimento   0.0000
ronco                                0.0000
tosse                                0.0000
fibrose_cistica                      0.0000
hipertermia                          0.0000
imunossuprimido                      0.0000
klebsiella                           0.0000
infeccao                             0.0000
leucopenia                           0.0000
moraxella                            0.0000
pneumococcus                         0.0000
leucocitose                          0.0000
sibilos                              0.0000
intubacao                            0.0000
staphylococcus_aureus                0.0000
sepse_pulmonar                       0.0000
sepse_respiratoria                   0.0000
sepse_urinaria                       0.0000
padrao_ventilatorio                  0.0000
pseudomonas                          0.0000
insuficiencia_ventilatoria           0.0000
esforco_ventilatorio                 0.0000
derrame_pleural                      0.0000
lavado_broncoalveolar                0.0000
choque_septico                       0.0000
dor_pleuritica                       0.0000
dor_ventilatorio_dependente          0.0000
o2                                   0.0000
linfoma                              0.0000
acinetobacter                        0.0000
amarelada                            0.0000
crepitante                           0.0000
enterobacter                         0.0000
enterococcus                         0.0000
hemophylus                           0.0000
cavita                               0.0000
mal_estar                            0.0000
rubor                                0.0000
supuracao                            0.0000
staphylococcus_coagulase_negativo    0.0000
mediastinite                         0.0000
hiperemia                            0.0000
eritema                              0.0000
ventilacao_mecanica                  0.0000
escherichia_coli                     0.0000
resistente                           0.0000
deiscencia                           0.0000
calor                                0.0000
endocardite                          0.0000
antibiotico                          0.0000
bacteriologico                       0.0000
abscesso                             0.0000
oliguria                             0.0000
hipotensao                           0.0000
anuria                               0.0000
bacteremia                           0.0000
bacteriuria                          0.0000
disuria                              0.0000
leucocituria                         0.0000
nitrito                              0.0000
svd                                  0.0000
tsa                                  0.0000
taquicardia                          0.0000
cateter_arterial                     0.0000
cateter_urinario                     0.0000
cvc                                  0.0000
cateter_venoso_periferico            0.0000
edema                                0.0000
calafrio                             0.0000
pos_operatorio                       0.0000
foco_urinario                        0.0000
dor_suprapubica                      0.0000
vomito                               0.0000
shigella                             0.0000
salmonela                            0.0000
colite_pseudomembranosa              0.0000
dor_cabeca                           0.0000
dor_abdominal                        0.0000
diarreia                             0.0000
clostridium                          0.0000
urgencia_urinaria                    0.0000
urgencia_miccional                   0.0000
sondagem_alivio                      0.0000
nausea                               0.0000
sondagem_vesical                     0.0000
urocultura                           0.0000
albumina                             0.0000
piuria                               0.0000
creatinina                           0.0000
glicose                              0.0000
plaquetas                            0.0000
press_parc_co2                       0.0000
bilirrubina                          0.0000
cardiomegalia                        0.0000
choque                               0.0000
staphylococcus                       0.0000
e_coli                               0.0000
colecao                              0.0000
tremor                               0.0000
instabilidade                        0.0000
freq_cardiaca                        0.0000
freq_respiratoria                    0.0000
pneumotorax                          0.0000
atelectasia                          0.0000
lesao_pulmonar                       0.0000
pneumonia                            0.0000
sibilancia                           0.0000
hipotermia                           0.0000
bradicardia                          0.0000
streptococcus_viridans               0.0000
hcm                                  0.0000
consciencia                          0.0000
hgm                                  0.0000
covid                                0.0000
hemocultura                          0.0000
saturacao_sangue                     0.0000
fio2                                 0.0000
peep                                 0.0000
desnutricao                          0.0000
sne                                  0.0000
fosfatase_alcalina                   0.0000
ldh                                  0.0000
cetamina                             0.0000
vsg                                  0.0000
propofol                             0.0000
clorpromazina                        0.0000
pancuronio                           0.0000
fentanil                             0.0000
noradrenalina                        0.0000
lorazepan                            0.0000
apneia                               0.0000
temperatura                          0.0000
clonidina                            0.0000
flumazenil                           0.0000
npt                                  0.0000
cateter_monolumen                    0.0000
portocath                            0.0000
cateter_hickmann                     0.0000
cateter_duplolumen                   0.0000
cateter_triplolumen                  0.0000
diabetes                             0.0000
neutropenia                          0.0000
pneumatose                           0.0000
piora_troca_gasosa                   0.0000
fontanela_abaulada                   0.0000
glicose_liquor                       0.0000
shilley                              0.0000
obesidade                            0.0000
leuco_liquor                         0.0000
prote_liquor                         0.0000
cultura_liquor                       0.0000
bacteria_liquor                      0.0000
hipoativ                             0.0000
dren_serosa                          0.0000
necrose_intestinal                   0.0000
irritabilidade                       0.0000
intestino_fixo                       0.0000
convulsao                            0.0000
dist_abdominal                       0.0000
pneumoperitonio                      0.0000
asp_bilioso                          0.0000
pcr                                  0.0000
letargia                             0.0000
int_alimentar                        0.0000
dtype: float64

In [47]:
text_tree = tree.export_text(model, feature_names=X_texto.columns)
print(text_tree)

|--- qtd_hemocultura_sem_crescimento <= 0.52
|   |--- qtd_cultura_positiva <= 1.09
|   |   |--- LEUCO_ALTERADO <= 0.06
|   |   |   |--- RDW_ALTO <= 0.41
|   |   |   |   |--- qtd_cultura_sem_crescimento <= 0.84
|   |   |   |   |   |--- leuco_min <= 19689.68
|   |   |   |   |   |   |--- neuto_avg <= 2073.63
|   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |--- neuto_avg >  2073.63
|   |   |   |   |   |   |   |--- leuco_avg <= 15573.79
|   |   |   |   |   |   |   |   |--- neuto_min <= 8714.82
|   |   |   |   |   |   |   |   |   |--- rdw_min <= 14.97
|   |   |   |   |   |   |   |   |   |   |--- neuto_min <= 6988.90
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4
|   |   |   |   |   |   |   |   |   |   |--- neuto_min >  6988.90
|   |   |   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |   |   |--- rdw_min >  14.97
|   |   |   |   |   |   |   |   |   |   |--- leuco_avg <= 11816.93
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- leuco_avg >  11816.93
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5
|   |   |   |   |   |   |   |   |--- neuto_min >  8714.82
|   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |--- leuco_avg >  15573.79
|   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |--- leuco_min >  19689.68
|   |   |   |   |   |   |--- class: False
|   |   |   |   |--- qtd_cultura_sem_crescimento >  0.84
|   |   |   |   |   |--- qtd_urocultura_sem_crescimento <= 0.55
|   |   |   |   |   |   |--- rdw_min <= 15.36
|   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |--- rdw_min >  15.36
|   |   |   |   |   |   |   |--- neuto_max <= 6697.30
|   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |--- neuto_max >  6697.30
|   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |--- qtd_urocultura_sem_crescimento >  0.55
|   |   |   |   |   |   |--- class: False
|   |   |   |--- RDW_ALTO >  0.41
|   |   |   |   |--- rdw_min <= 21.33
|   |   |   |   |   |--- class: False
|   |   |   |   |--- rdw_min >  21.33
|   |   |   |   |   |--- neuto_avg <= 4435.35
|   |   |   |   |   |   |--- class: True
|   |   |   |   |   |--- neuto_avg >  4435.35
|   |   |   |   |   |   |--- class: True
|   |   |--- LEUCO_ALTERADO >  0.06
|   |   |   |--- qtd_cultura_positiva <= 0.54
|   |   |   |   |--- qtd_cultura_sem_crescimento <= 3.90
|   |   |   |   |   |--- qtd_cultura_sem_crescimento <= 1.67
|   |   |   |   |   |   |--- sedacao <= 0.59
|   |   |   |   |   |   |   |--- dreno <= 0.22
|   |   |   |   |   |   |   |   |--- consol <= 0.25
|   |   |   |   |   |   |   |   |   |--- infil <= 0.86
|   |   |   |   |   |   |   |   |   |   |--- iot <= 0.11
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5
|   |   |   |   |   |   |   |   |   |   |--- iot >  0.11
|   |   |   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |   |   |--- infil >  0.86
|   |   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |   |--- consol >  0.25
|   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |--- dreno >  0.22
|   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |--- sedacao >  0.59
|   |   |   |   |   |   |   |--- dreno <= 0.01
|   |   |   |   |   |   |   |   |--- opac <= 0.43
|   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |   |--- opac >  0.43
|   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |--- dreno >  0.01
|   |   |   |   |   |   |   |   |--- LEUCO_ALTERADO <= 1.00
|   |   |   |   |   |   |   |   |   |--- LEUCO_ALTO <= 0.76
|   |   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |   |   |--- LEUCO_ALTO >  0.76
|   |   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |   |--- LEUCO_ALTERADO >  1.00
|   |   |   |   |   |   |   |   |   |--- qtd_cultura_sem_crescimento <= 0.02
|   |   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |   |   |--- qtd_cultura_sem_crescimento >  0.02
|   |   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |--- qtd_cultura_sem_crescimento >  1.67
|   |   |   |   |   |   |--- spo2 <= 0.00
|   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |--- spo2 >  0.00
|   |   |   |   |   |   |   |--- qtd_cultura_sem_crescimento <= 2.09
|   |   |   |   |   |   |   |   |--- qtd_urocultura_sem_crescimento <= 0.60
|   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |   |--- qtd_urocultura_sem_crescimento >  0.60
|   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |--- qtd_cultura_sem_crescimento >  2.09
|   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |--- qtd_cultura_sem_crescimento >  3.90
|   |   |   |   |   |--- class: True
|   |   |   |--- qtd_cultura_positiva >  0.54
|   |   |   |   |--- class: True
|   |--- qtd_cultura_positiva >  1.09
|   |   |--- qtd_urocultura_positiva <= 0.30
|   |   |   |--- qtd_cultura_sem_crescimento <= 1.52
|   |   |   |   |--- rdw_min <= 20.24
|   |   |   |   |   |--- class: True
|   |   |   |   |--- rdw_min >  20.24
|   |   |   |   |   |--- qtd_cultura_positiva <= 2.22
|   |   |   |   |   |   |--- qtd_hemocultura_positiva <= 0.61
|   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |--- qtd_hemocultura_positiva >  0.61
|   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |--- qtd_cultura_positiva >  2.22
|   |   |   |   |   |   |--- class: True
|   |   |   |--- qtd_cultura_sem_crescimento >  1.52
|   |   |   |   |--- qtd_cultura_sem_crescimento <= 2.65
|   |   |   |   |   |--- qtd_urocultura_sem_crescimento <= 0.55
|   |   |   |   |   |   |--- qtd_cultura_positiva <= 3.96
|   |   |   |   |   |   |   |--- qtd_cultura_positiva <= 2.41
|   |   |   |   |   |   |   |   |--- qtd_hemocultura_positiva <= 0.21
|   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |   |--- qtd_hemocultura_positiva >  0.21
|   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |--- qtd_cultura_positiva >  2.41
|   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |--- qtd_cultura_positiva >  3.96
|   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |--- qtd_urocultura_sem_crescimento >  0.55
|   |   |   |   |   |   |--- class: True
|   |   |   |   |--- qtd_cultura_sem_crescimento >  2.65
|   |   |   |   |   |--- class: False
|   |   |--- qtd_urocultura_positiva >  0.30
|   |   |   |--- class: False
|--- qtd_hemocultura_sem_crescimento >  0.52
|   |--- qtd_cultura_sem_crescimento <= 3.55
|   |   |--- qtd_cultura_positiva <= 1.83
|   |   |   |--- int_glicose <= 0.00
|   |   |   |   |--- pressao_sanguinea <= 0.34
|   |   |   |   |   |--- class: False
|   |   |   |   |--- pressao_sanguinea >  0.34
|   |   |   |   |   |--- class: False
|   |   |   |--- int_glicose >  0.00
|   |   |   |   |--- leuco_max <= 3231.78
|   |   |   |   |   |--- leuco_avg <= 1761.07
|   |   |   |   |   |   |--- class: True
|   |   |   |   |   |--- leuco_avg >  1761.07
|   |   |   |   |   |   |--- class: True
|   |   |   |   |--- leuco_max >  3231.78
|   |   |   |   |   |--- LEUCO_BAIXO <= 0.60
|   |   |   |   |   |   |--- rdw_max <= 16.31
|   |   |   |   |   |   |   |--- LEUCO_ALTERADO <= 0.87
|   |   |   |   |   |   |   |   |--- rdw_max <= 15.11
|   |   |   |   |   |   |   |   |   |--- neuto_avg <= 5626.87
|   |   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |   |   |--- neuto_avg >  5626.87
|   |   |   |   |   |   |   |   |   |   |--- NEUTROFILO_ALTO <= 0.09
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- NEUTROFILO_ALTO >  0.09
|   |   |   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |   |--- rdw_max >  15.11
|   |   |   |   |   |   |   |   |   |--- rdw_min <= 15.21
|   |   |   |   |   |   |   |   |   |   |--- neuto_min <= 6000.68
|   |   |   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |   |   |   |--- neuto_min >  6000.68
|   |   |   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |   |   |--- rdw_min >  15.21
|   |   |   |   |   |   |   |   |   |   |--- rdw_max <= 15.59
|   |   |   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |   |   |   |--- rdw_max >  15.59
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 11
|   |   |   |   |   |   |   |--- LEUCO_ALTERADO >  0.87
|   |   |   |   |   |   |   |   |--- neuto_avg <= 15174.94
|   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |   |--- neuto_avg >  15174.94
|   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |--- rdw_max >  16.31
|   |   |   |   |   |   |   |--- leuco_max <= 13367.18
|   |   |   |   |   |   |   |   |--- neuto_min <= 4908.17
|   |   |   |   |   |   |   |   |   |--- neuto_min <= 4394.66
|   |   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |   |   |--- neuto_min >  4394.66
|   |   |   |   |   |   |   |   |   |   |--- leuco_min <= 8695.99
|   |   |   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |   |   |   |--- leuco_min >  8695.99
|   |   |   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |   |--- neuto_min >  4908.17
|   |   |   |   |   |   |   |   |   |--- leuco_min <= 12178.11
|   |   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |   |   |--- leuco_min >  12178.11
|   |   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |--- leuco_max >  13367.18
|   |   |   |   |   |   |   |   |--- LEUCO_ALTO <= 0.54
|   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |   |--- LEUCO_ALTO >  0.54
|   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |--- LEUCO_BAIXO >  0.60
|   |   |   |   |   |   |--- leuco_avg <= 4185.11
|   |   |   |   |   |   |   |--- neuto_max <= 945.47
|   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |--- neuto_max >  945.47
|   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |--- leuco_avg >  4185.11
|   |   |   |   |   |   |   |--- class: True
|   |   |--- qtd_cultura_positiva >  1.83
|   |   |   |--- neuto_min <= 1002.33
|   |   |   |   |--- class: True
|   |   |   |--- neuto_min >  1002.33
|   |   |   |   |--- rdw_max <= 19.67
|   |   |   |   |   |--- neuto_avg <= 3931.36
|   |   |   |   |   |   |--- class: True
|   |   |   |   |   |--- neuto_avg >  3931.36
|   |   |   |   |   |   |--- class: True
|   |   |   |   |--- rdw_max >  19.67
|   |   |   |   |   |--- qtd_hemocultura_positiva <= 0.93
|   |   |   |   |   |   |--- qtd_cultura_positiva <= 2.84
|   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |--- qtd_cultura_positiva >  2.84
|   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |--- qtd_hemocultura_positiva >  0.93
|   |   |   |   |   |   |--- class: True
|   |--- qtd_cultura_sem_crescimento >  3.55
|   |   |--- sangue_fezes <= 0.00
|   |   |   |--- dreno <= 0.40
|   |   |   |   |--- class: False
|   |   |   |--- dreno >  0.40
|   |   |   |   |--- class: False
|   |   |--- sangue_fezes >  0.00
|   |   |   |--- qtd_urocultura_sem_crescimento <= 1.19
|   |   |   |   |--- qtd_urocultura_sem_crescimento <= 0.23
|   |   |   |   |   |--- qtd_cultura_positiva <= 0.68
|   |   |   |   |   |   |--- qtd_cultura_sem_crescimento <= 4.44
|   |   |   |   |   |   |   |--- qtd_hemocultura_sem_crescimento <= 1.69
|   |   |   |   |   |   |   |   |--- LEUCO_ALTERADO <= 0.44
|   |   |   |   |   |   |   |   |   |--- NEUTROFILO_ALTO <= 0.20
|   |   |   |   |   |   |   |   |   |   |--- neuto_avg <= 5442.22
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- neuto_avg >  5442.22
|   |   |   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |   |   |--- NEUTROFILO_ALTO >  0.20
|   |   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |   |--- LEUCO_ALTERADO >  0.44
|   |   |   |   |   |   |   |   |   |--- LEUCO_ALTERADO <= 1.00
|   |   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |   |   |--- LEUCO_ALTERADO >  1.00
|   |   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |--- qtd_hemocultura_sem_crescimento >  1.69
|   |   |   |   |   |   |   |   |--- neuto_avg <= 2693.23
|   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |   |--- neuto_avg >  2693.23
|   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |--- qtd_cultura_sem_crescimento >  4.44
|   |   |   |   |   |   |   |--- qtd_hemocultura_sem_crescimento <= 1.49
|   |   |   |   |   |   |   |   |--- neuto_min <= 7096.80
|   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |   |--- neuto_min >  7096.80
|   |   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |   |--- qtd_hemocultura_sem_crescimento >  1.49
|   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |--- qtd_cultura_positiva >  0.68
|   |   |   |   |   |   |--- neuto_avg <= 6102.07
|   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |--- neuto_avg >  6102.07
|   |   |   |   |   |   |   |--- qtd_hemocultura_sem_crescimento <= 1.71
|   |   |   |   |   |   |   |   |--- qtd_hemocultura_positiva <= 0.86
|   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |   |--- qtd_hemocultura_positiva >  0.86
|   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |--- qtd_hemocultura_sem_crescimento >  1.71
|   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |--- qtd_urocultura_sem_crescimento >  0.23
|   |   |   |   |   |--- LEUCO_ALTERADO <= 0.03
|   |   |   |   |   |   |--- qtd_cultura_sem_crescimento <= 6.48
|   |   |   |   |   |   |   |--- qtd_hemocultura_sem_crescimento <= 1.00
|   |   |   |   |   |   |   |   |--- qtd_cultura_sem_crescimento <= 5.79
|   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |   |--- qtd_cultura_sem_crescimento >  5.79
|   |   |   |   |   |   |   |   |   |--- neuto_min <= 10255.12
|   |   |   |   |   |   |   |   |   |   |--- rdw_avg <= 15.04
|   |   |   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |   |   |   |--- rdw_avg >  15.04
|   |   |   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |   |   |--- neuto_min >  10255.12
|   |   |   |   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |   |   |--- qtd_hemocultura_sem_crescimento >  1.00
|   |   |   |   |   |   |   |   |--- class: False
|   |   |   |   |   |   |--- qtd_cultura_sem_crescimento >  6.48
|   |   |   |   |   |   |   |--- class: True
|   |   |   |   |   |--- LEUCO_ALTERADO >  0.03
|   |   |   |   |   |   |--- class: True
|   |   |   |--- qtd_urocultura_sem_crescimento >  1.19
|   |   |   |   |--- qtd_urocultura_sem_crescimento <= 2.40
|   |   |   |   |   |--- class: False
|   |   |   |   |--- qtd_urocultura_sem_crescimento >  2.40
|   |   |   |   |   |--- class: False